export const COLORS = {
  ENGLISH_VIOLET: '#473A55',
  CADET_GREY: '#A0ADBC',
  GHOST_WHITE: '#F0F4FC',
  WHITE: '#FFFFFF',
  PERSIAN_BLUE: '#2F3BAD',
  NEON_BLUE: '#566DFB',
  AQUAMARINE: '#5EDBAE',
  INDIAN_RED: '#E24E58',
  DARK_POSTAL_GREEN: '#34B549',
};
